### ISSUE TITLE
No module named 'slackclient'

### ISSUE THREAD

**Issue by tr4nscr1pt** [JPStrydom/Crypto-Trading-Bot#10]
python3.6 app.py

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from messenger import Messenger
  File "/home/node/Crypto-Trading-Bot/src/messenger.py", line 3, in <module>
    from slackclient import SlackClient
ModuleNotFoundError: No module named 'slackclient'

**Comment by JPStrydom** [comment]
1) Are you on the latest version of the code-base (i.e. are you up to track with the current master branch)?
2) Have you installed all the requirements as mentioned in the README?

**Comment by tr4nscr1pt** [comment]
I installed it later with pip3. Thanks

**Comment by JPStrydom** [comment]
Let me know if this isn't fixed 👍

**Comment by JPStrydom** [comment]
If anyone else comes across this issue, try running `sudo pip3 install -r requirements.txt` instead to install the dependencies.

**Comment by crazy161** [comment]
I got the similar issue when executing airflow job, it looks like the slack api changed a bit after `pip install slackclient`.

```py
## before
from slackclient import SlackClient
client = SlackClient(self.token)
## after
import slack
client = slack.RTMClient(self.token)
```
Reference: [slack api change](https://github.com/slackapi/python-slackclient/wiki/Migrating-to-2.x)

**Comment by bernej** [comment]
Thank you @zzz686970 

Indeed it appears migrating from slackclient 1.3.x to 2.0.x is the reason behind this.

Additionally, slackclient.SlackClient's new moniker is slack.WebClient
```python
from slackclient import SlackClient   ======>   from slack import WebClient
```
