### ISSUE TITLE
Actual profit/loss

### ISSUE THREAD

**Issue by dr333** [JPStrydom/Crypto-Trading-Bot#11]
I am not sure if this is an issue or perhaps I am missing something. The profit/loss calculation in the current implementation seems to take into account only the 'quantity' value of the BTC before and after the SELL. It does not account for any corresponding FIAT value and so what appears to be profit may not be an actual profit but rather a loss, say for e.g. if the current price value of BTC (in USD) has dropped. Again, sorry if I have missed something basic here, but would appreciate if someone could validate this. Perhaps this is how the strategy was intended to be but I am not sure.

**Comment by JPStrydom** [comment]
Yeah the profit looks at coin's BTC value - which is its value on the
market it's being traded on. USDT-BTC is a different market all together.

**Comment by dr333** [comment]
I see, thank you for clarifying this. Given that, any suggestions on how to account for 'true' profit/loss? The bot currently sells for the configured profit margin but in reality its a loss since the BTC price has dropped significantly.

**Comment by JPStrydom** [comment]
You'd have to tweak the system to calculate your profit based on the coin
-> BTC -> USDT arbitrage.
