### ISSUE TITLE
Unsupported operand type(s) for *: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by Joshaboc** [JPStrydom/Crypto-Trading-Bot#17]
I'm assuming the second error is what's causing the main problems. 

2018/05/01 11:36:44 AM - ERROR: Failed to fetch Bittrex market summary for the BTC-USDT market.
2018/05/01 11:36:44 AM - ERROR: unsupported operand type(s) for *: 'NoneType' and 'float'
Traceback (most recent call last):
  File "C:\Users\bmw18\Desktop\Crypto-Trading-Bot-master\src\trader.py", line 429, in create_balance_object
    btc_value = round(btc_price * balance_item["Balance"], 8)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

**Comment by JPStrydom** [comment]
When was the last time you pulled the project? I rolled out a fix for this issue yesterday. If it persists on the latest code, please lemme know.

**Comment by JPStrydom** [comment]
Closing this as it's a duplicate of #15
