### ISSUE TITLE
No buying after a buy is done?

### ISSUE THREAD

**Issue by signalpower** [JPStrydom/Crypto-Trading-Bot#18]
From the logs it looks like there is no attempt to buy after one buy is done. I only see No sell logs.
If the current code only allows one buy/sell I'd love to see the possibility of several buy and sell orders.

**Comment by JPStrydom** [comment]
This is how it's intended to function, and how it's explained in the README.  If you don't focus on a sale you might miss on a profit or go into a loss. 
There is pause functionality which allows you to temporarily pause sells that run too long - this is also explained in the documentation.
