### ISSUE TITLE
this is my vefry first time trying this, i followed step by step but still got this error

### ISSUE THREAD

**Issue by CryptoRootz** [JPStrydom/Crypto-Trading-Bot#20]
Crypto-Trading-Bot-master\src>python app.py
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from messenger import Messenger
  File "C:\Users\Dready\Desktop\crypto files\Crypto-Trading-Bot-master\src\messenger.py", line 3, in <module>
    from slackclient import SlackClient
ModuleNotFoundError: No module named 'slackclient'

**Comment by JPStrydom** [comment]
Hi! This issue is occurring because the requirements aren't properly installed.

If you're on Linux you can try `sudo pip3 install -r requirements.txt`, else you can try manually installing the missing packages (in this case the `slackclient` package)

**Comment by JPStrydom** [comment]
You can see #10 that discusses this issue as well.

**Comment by JPStrydom** [comment]
Closing this as it's a duplicate issue
