### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by aintnocode** [JPStrydom/Crypto-Trading-Bot#3]
except (IOError, json.decoder.JSONDecodeError):
AttributeError: 'module' object has no attribute 'JSONDecodeError'

**Comment by soufiane8096** [comment]
Same here !

**Comment by HansLe** [comment]
I downloaded the code today. This problem didnt occur. I think it will have to do with the secrets.json file. Copy following text in de secrets.json file. Off coure you have to mentionl your own bittrex info.

{
    "bittrex": {
        "bittrexKey": "your key",
        "bittrexSecret": "your secret key"
    },
    "sound": false,
    "tradeParameters": {
        "tickerInterval": "fiveMin",
        "buy": {
            "btcAmount": 0.001,
            "rsiThreshold": 20,
            "24HourVolumeThreshold": 25,
            "minimumUnitPrice": 0.00001,
            "maxOpenTrades": 3
        },
        "sell": {
            "rsiThreshold": 50,
            "minProfitMarginThreshold": 0.5,
            "profitMarginThreshold": 2.5
        }
    },
    "pauseParameters": {
        "buy": {
            "rsiThreshold": 0,
            "pauseTime": 0
        },
        "sell": {
            "profitMarginThreshold": 0,
            "pauseTime": 0
        }
    }
}

**Comment by JPStrydom** [comment]
Is anyone still experiencing this issue?

**Comment by aintnocode** [comment]
i am still experiencing this issue. tried with the code HansLe provided but no difference

**Comment by JPStrydom** [comment]
@aintnocode Mind running it and then sending me your latest log file?

**Comment by windowsxp811203** [comment]
2018/02/17 01:35:28 AM - ERROR: Failed to buy on BTC-EXP market.
2018/02/17 01:35:57 AM - ERROR: Failed to buy on BTC-DCR market.
2018/02/17 01:36:08 AM - ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:/Trading/Crypto-Trading-Bot-master/src/app.py", line 91, in <module>
    Trader.analyse_buys()
  File "C:\Trading\Crypto-Trading-Bot-master\src\trader.py", line 55, in analyse_buys
    self.buy_strategy(coin_pair)
  File "C:\Trading\Crypto-Trading-Bot-master\src\trader.py", line 77, in buy_strategy
    current_buy_price = self.get_current_price(coin_pair, "ask")
  File "C:\Trading\Crypto-Trading-Bot-master\src\trader.py", line 245, in get_current_price
    coin_summary = self.Bittrex.get_market_summary(coin_pair)
  File "C:\Trading\Crypto-Trading-Bot-master\src\bittrex.py", line 209, in get_market_summary
    return self.api_query("getmarketsummary", {"market": market})
  File "C:\Trading\Crypto-Trading-Bot-master\src\bittrex.py", line 129, in api_query
    return self.dispatch(request_url, apisign)
  File "C:\Trading\Crypto-Trading-Bot-master\src\bittrex.py", line 67, in using_requests
    headers={"apisign": apisign}
  File "C:\Trading\Crypto-Trading-Bot-master\venv\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\windo\AppData\Local\Programs\Python\Python36-32\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\windo\AppData\Local\Programs\Python\Python36-32\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\windo\AppData\Local\Programs\Python\Python36-32\Lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by danielaxford** [comment]
@windowsxp811203 unfortunately, this is just the Bittrex server returning an empty result in the api query response and during high load times this can occur quite frequently. The only workaround I have found so far in order to account for the Bittrex server is to implement a Try, Except for the api request query.

def using_requests(request_url, apisign):
    while True:
        try:
            response = requests.get(request_url, headers={"apisign": apisign}).json()
        except (requests.exceptions.RequestException, json.decoder.JSONDecodeError, ValueError) as e:
            logger.exception(e)
            continue
        else:
            return response

I believe json.decoder.JSONDecodeError inherits ValueError but I prefer to catch the specific exception in the logger.

**Comment by JPStrydom** [comment]
Yeah @danielaxford is correct. I do run the entire program in a `try` statement. Sometimes the buys/sales fail because the amount you're trying to buy/sell isn't available due to other buys/sales going through. They system will adjust to these errors but will still notify with an error message.

**Comment by JPStrydom** [comment]
If anyone has this issues, let me know. I'm going to close this for now seeing as it's inactive.
