### ISSUE TITLE
very similar to Dovewallet structure

### ISSUE THREAD

**Issue by alimogh** [JPStrydom/Crypto-Trading-Bot#31]
**Hello
please rewrite other project for Dovewallet.
bittrex v1.1 compatible & similar with Dovewallet
Link help Api [https://developer.dovewallet.com/api/v1/](url)
Thanks.**

**Comment by JPStrydom** [comment]
Hi!

This library is no longer maintained as I just don't have the time to support it. But you're very welcome to check out the [QuidPro](https://quidpro.co/) web and mobile application - it has all the functionality of this tool and much more. It allows you to do live trading with bots you can customise, and it allows you to participate in fantastic trading tournament against other players' bots.

Thanks for the support!
