### ISSUE TITLE
Invalid Key

### ISSUE THREAD

**Issue by Ghost-Tech** [JPStrydom/Crypto-Trading-Bot#4]
I keep getting the following error message:
_Invalid key provided to obj/dict_

I've checked the api keys and secrets, tried creating new ones. but I always get this error.

**Comment by HansLe** [comment]
I got this message too. Probaly you used the example of the secrets.json as mentioned on the "home" page.

Enter the following lines in de secrets.json pauseparamaters area:
        "buy": {
            "rsiThreshold": 0,
            "pauseTime": 0
        },
        "sell": {
            "profitMarginThreshold": 0,
            "pauseTime": 0
        }

**Comment by JPStrydom** [comment]
Hi all! Sorry for leaving this out of the example and the generated template. I'll have a look into fixing it asap!

**Comment by JPStrydom** [comment]
Thanks @HansLe for the fix!

**Comment by jrbadiabo** [comment]
@HansLe @JPStrydom Could you explain why we have to put this piece of code in the secrets.json file?
I had the same issue and it's resolved thanks to HansLe comment but it sounds now that this piece of code is duplicated in both settings.json and secrets.json.
Do I have to change the parameters in both files now if I want to change the trade settings?

Thanks in advance guys,

**Comment by JPStrydom** [comment]
@jrbadiabo have a look at the README, it explains everything in detail.

**Comment by Pr3datorg** [comment]
It seems you need to add this code to the Instructions page.. You have what should be a Good file Mentioned to copy but it does not include these items. if you just have the Pause {} then it wont work.
